server:
  servlet:
    context-path: /
  port: 9100

spring:
  application:
    name: sagittarius

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/jpademo?serverTimezone=GMT%2B8
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5level [%15thread] %-50.50(%logger{39}.%method:%-3line) - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr([%15thread]){faint} %clr(%-50.50(%logger{39}.%method:%-3line)){cyan} %clr(-){faint} %msg%n"
  file: ../logs/sagittarius/sagittarius.log
  file.max-history: 30
  level:
    com.huibo.sagittarius: info